# Generated by Django 4.0.4 on 2022-05-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intents',
            old_name='pattern',
            new_name='patterns',
        ),
        migrations.RenameField(
            model_name='intents',
            old_name='response',
            new_name='responses',
        ),
    ]
